spring:
  config:
    import: "optional:configserver:http://config-server:8888"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    circuitbreaker:
      resilience4j:
        enabled: true
    main:
      web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: "http://eureka-server:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
